### ISSUE TITLE
Error when using empty Database in GUI

### ISSUE THREAD

**Issue by JonasHoelscher** [upb-lea/transistordatabase#97]
**Describe the bug**
Traceback (most recent call last):
  File "/home/nikolasf/Dokumente/01_git/30_Python/TDB/transistordatabase/gui/gui.py", line 5852, in <module>
    MainWindow = MainWindow()
  File "/home/nikolasf/Dokumente/01_git/30_Python/TDB/transistordatabase/gui/gui.py", line 191, in __init__
    self.comboBox_topology_transistor1_changed()
  File "/home/nikolasf/Dokumente/01_git/30_Python/TDB/transistordatabase/gui/gui.py", line 4695, in comboBox_topology_transistor1_changed
    self.comboBox_topology_transistor_changed(self.comboBox_topology_transistor1,
  File "/home/nikolasf/Dokumente/01_git/30_Python/TDB/transistordatabase/gui/gui.py", line 4594, in comboBox_topology_transistor_changed
    available_v_g_on_transistor = [str(channel.v_g) for channel in transistor.switch.channel]
AttributeError: 'NoneType' object has no attribute 'switch'
Exception ignored in: <__main__.EmittingStream object at 0x7f0160aab760>
RuntimeError: wrapped C/C++ object of type EmittingStream has been deleted

Currently the GUI uses a database which is in the folder transistordatabase/database. If there is no Database (e.g. it is empty) this error is thrown. This is due to a load_transistor which returns a None object when the transistor is not found in the Database.

Fix: Add a check for the transistor value and only proceed when the transistor is not None

**To Reproduce**
Open GUI without the transistordatabase/database folder (or with an empty folder)

**Expected behavior**
The GUI should be shown.

**Comment by Sarim-Zuhair** [comment]
The issue has been fixed in the latest commit
